### PR TITLE
Make add transaction to be in one database transaction

### PR DESCRIPTION
**Pull request by vzool**

### CODE REVIEW

**Comment by darcys22** [comment]
This is amazing, thank you! Appreciate the pull request.

ill have a play with this tonight and give it some testing

**Comment by vzool** [comment]
BTW, why we don't just add "[Trading Simulator](https://github.com/darcys22/Trading-Simulator)" as  an extra extensive test inside "[godbledger](https://github.com/darcys22/godbledger)" itself?

**Comment by darcys22** [comment]
I love that idea, i had been reworking the integration tests over the holiday period so i could start doing lots of complicated testing in the CI. Right now the tests i have built are basic, you can see them in `tests/evaluators` but the trading simulator could almost be copied and pasted into one of those evaluators. Appreciate the feedback!

**Comment by darcys22** [comment]
Alright, so this works perfectly on my end. Also is noticeably faster when submitting using the `send_transaction` method.

Thanks again! appreciate the amazing work

**Comment by vzool** [comment]
> Alright, so this works perfectly on my end. Also is noticeably faster when submitting using the `send_transaction` method.
> 
> Thanks again! appreciate the amazing work

You're very welcome :)

**Pull request merged**
