### PR TITLE
GH-84 Add basic dockerfile and some docker-based make targets

### PR DESCRIPTION
**Pull request by davidalpert**
allows running `make build-docker` (or `make docker-build`)
to build the 3 godbledger binaries into a docker image.

`make docker-start` will start up `mysql` and `godbledger` in docker forwarding
ports 3306 and 50051 respectively

`make docker-stop` will stop and remove both containers

`make docker-login` will log into an `ash` shell in the
godbledger container, mounting it if it's not already running, or
exec'ing into the running container if it is.

### CODE REVIEW

**Comment by darcys22** [comment]
This is awesome! Appreciate the amazing work as always.

Had a few minor comments:

1) I've used the mysql credentials around in other areas as `USER:godbledger PASS:password` and for consistency would prefer to keep this convention. There is a command that could be called from the local machine `godbledger init -m` which creates the below config file (Assuming they have the godbledger executable locally though) and I believe this would allow them to communicate with the docker container, might be worth adding the charset parameter to this code. This can be seen in `godbledger/cmd/config.go:162:`

```
Host = "127.0.0.1"
RPCPort = "50051"
CACert = ""
Cert = ""
Key = ""
DataDirectory = "/home/sean/.ledger"
LogVerbosity = "debug"
ConfigFile = "/home/sean/.ledger/config.toml"
DatabaseType = "mysql"
DatabaseLocation = "godbledger:password@tcp(127.0.0.1:3306)/ledger"
```

2) Could `wait_entrypoint.sh` be moved into the utils directory rather than the root directory?

**Comment by davidalpert** [comment]
very much appreciate the feedback.
- [ ] will update the PR to match those default credentials;
- [ ] will update `config.go` to include the charset params if they make sense and seem right as they are;
- [ ] will move `wait_entrypoint.sh` to the utils directory;

**Comment by davidalpert** [comment]
I moved `Dockerfile.build` into `./utils` also since it doesn't need to be at the root, but it does assume that it is invoked from the root, as is done in the updated `make docker-build` command.

I also noticed that the DSN string (including mysql password) was logged at debug level, so I added a simple regexp and filter to REDACT the mysql connection string password when printing to the logs.

**Comment by darcys22** [comment]
Amazing, works perfectly!

**Pull request merged**
